config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "sidekiq/web"

  mount Sidekiq::Web, at: "/sidekiq", constraints: AdminConstraint.new

  root to: "welcome#index"

  resource :account, only: [:new, :create, :show, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  namespace :target do
    resources :refreshes, only: [:create]
  end

  resources :checks, only: [:index, :new, :edit, :update, :destroy] do
    resources :counts, only: [:new, :create], controller: "check_counts"
  end

  resources :trello_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "trello_checks"
  end

  resources :github_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "github_checks"
  end

  resources :manual_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "manual_checks"
  end

  get "/trello_integrations/create", to: "trello_integrations#create"
  get "/github_integrations/create", to: "github_integrations#create"

  if Rails.env.test? && ENV["FAKE_APIS"] != "false"
    require_relative "routes/fake_api"
  end
end

app/controllers/trello_checks_controller.rb
# frozen_string_literal: true

class TrelloChecksController < ApplicationController
  def new
    render(locals: { check:, trello_integration: })
  end

  def create
    check.save!
    Check::Refresh.call(check)

    redirect_to(checks_path)
  end

  private

  def check
    @check ||= Check::Trello::ListHasCards.new(check_params)
  end

  def trello_integration
    @trello_integration ||=
      current_user.integrations.find(params.fetch(:trello_integration_id))
  end

  def base_params
    {
      user: current_user,
      integration: trello_integration,
      target_attributes: {},
    }
  end

  def check_params
    check_params =
      if params.key?(:check)
        params.expect(check: [:board_id, :list_id, :name])
      else
        {}
      end
    check_params.merge(base_params)
  end
end

app/views/trello_checks/_board_id.html.haml
%h2 Pick a board

- submit_path = new_trello_integration_check_path(trello_integration)
= form_with(model: check, url: submit_path, method: :get) do |form|
  = form.label(:board_id, "Boards")
  = form.collection_select(:board_id, check.fetch_boards, :id, :name)

  = form.submit("Next")

app/views/trello_checks/_list_id.html.haml
%h2 Pick a list

- submit_path = new_trello_integration_check_path(trello_integration)
= form_with(model: check, url: submit_path, method: :get) do |form|
  = form.hidden_field(:board_id)
  = form.label(:list_id, "Lists")
  = form.collection_select(:list_id, check.lists, :id, :name)

  = form.submit("Next")

app/views/trello_checks/_name.html.haml
%h2 Name your check

- submit_path = trello_integration_checks_path(trello_integration)
= form_with(model: check, url: submit_path) do |form|
  = form.hidden_field(:board_id)
  = form.hidden_field(:list_id)
  = form.label(:name)
  = form.text_field(:name)

  = form.submit("Done")

app/views/trello_checks/new.html.haml
= render(check.next_step, check:, trello_integration:)