config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require "sidekiq/web"

  mount Sidekiq::Web, at: "/sidekiq", constraints: AdminConstraint.new

  root to: "welcome#index"

  resource :account, only: [:new, :create, :show, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  namespace :target do
    resources :refreshes, only: [:create]
  end

  resources :checks, only: [:index, :new, :edit, :update, :destroy] do
    resources :counts, only: [:new, :create], controller: "check_counts"
  end

  resources :trello_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "trello_checks"
  end

  resources :github_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "github_checks"
  end

  resources :manual_integrations, only: [:new] do
    resources :checks, only: [:new, :create], controller: "manual_checks"
  end

  get "/trello_integrations/create", to: "trello_integrations#create"
  get "/github_integrations/create", to: "github_integrations#create"

  if Rails.env.test? && ENV["FAKE_APIS"] != "false"
    require_relative "routes/fake_api"
  end
end

app/models/check.rb
# frozen_string_literal: true

class Check < ApplicationRecord
  belongs_to :user
  belongs_to :integration
  belongs_to :latest_count, class_name: "Count"
  has_one :target, dependent: :delete
  has_many :counts, dependent: :delete_all

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :integration_id, :user_id, :target, presence: true

  accepts_nested_attributes_for :target, update_only: true

  scope(
    :last_counted_before,
    lambda { |timestamp|
      left_joins(:counts)
          .having(
            "MAX(counts.created_at) < ? OR COUNT(counts) = 0",
            timestamp,
          )
          .group("checks.id")
    },
  )

  delegate :value, to: :target, prefix: true

  def self.model_name
    ActiveModel::Name.new(base_class)
  end

  def manual?
    false
  end

  def active?
    last_value.present? && last_value > target.value
  end

  def refresh=(refresh)
    Check::Refresh.call(self) if ["true", true].include?(refresh)
  end

  def next_count
    raise NotImplementedError, "next_count should be implemented on sub-classes"
  end

  def last_value
    latest_count && latest_count.value
  end
end

app/models/check/github/user_has_assigned_pull_requests.rb
# frozen_string_literal: true

class Check::Github::UserHasAssignedPullRequests < Check
  delegate :pull_requests, to: :integration

  STEPS = ["name"].freeze

  def service
    "GitHub"
  end

  def icon
    ["fab", "github"]
  end

  def next_count
    pull_requests.count
  end

  def next_step
    STEPS.find { |step| public_send(step).nil? }
  end

  def url
    "#{integration.web_endpoint}pulls/assigned"
  end
end

app/models/check/manual/any_count.rb
# frozen_string_literal: true

class Check::Manual::AnyCount < Check
  include Rails.application.routes.url_helpers

  STEPS = ["name"].freeze

  def next_step
    STEPS.find { |step| public_send(step).nil? }
  end

  def service
    "manual"
  end

  def icon
    ["fas", "exclamation"]
  end

  def manual?
    true
  end

  def url
    new_check_count_path(self)
  end
end

app/models/check/trello/list_has_cards.rb
# frozen_string_literal: true

class Check::Trello::ListHasCards < Check
  store_accessor :data, :board_id, :list_id
  validates :board_id, :list_id, presence: true
  delegate :fetch_boards, to: :integration
  delegate :url, to: :board

  STEPS = ["board_id", "list_id", "name"].freeze

  def service
    "Trello"
  end

  def icon
    ["fab", "trello"]
  end

  def next_count
    cards.count
  end

  def next_step
    STEPS.find { |step| public_send(step).nil? }
  end

  def board
    integration.fetch_board(id: board_id)
  end

  def cards
    integration.fetch_cards(list_id:)
  end

  def lists
    integration.fetch_lists(board_id:)
  end
end

app/controllers/checks_controller.rb
# frozen_string_literal: true

class ChecksController < ApplicationController
  def index
    checks = current_user.checks.preload(:latest_count, :target, :integration)
    targets = current_user.targets.unreached_goal

    render(locals: { checks:, unreached_goal_targets: targets })
  end

  def new; end

  def edit
    render(locals: { check: find_check(params[:id]) })
  end

  def update
    check = find_check(params[:id])
    if check.update(check_params)
      flash[:success] = "Check updated"
      redirect_to(checks_path)
    else
      flash.now[:error] = "Unable to update check"
      render(:edit, locals: { check: })
    end
  end

  def destroy
    Check::Destroy.call(find_check(params[:id]))

    flash[:success] = "Check deleted"
    redirect_to(checks_path)
  end

  private

  def target_attributes
    [:value, :id, :delta, :goal_value]
  end

  def check_params
    params.expect(check: [:name, :refresh, { target_attributes: }])
  end

  def find_check(id)
    current_user.checks.preload(:integration, :target).find(id)
  end
end

app/views/checks/_list.html.haml
.card-list
  - checks.each do |check|
    .card
      .card-main
        .check-values
          %span.check-value= check.last_value
          = icon("fas", "arrow-right", class: "fa-2x")
          %span.check-value.target-value= check.target_value
        %h3
          = icon(*check.icon, class: "fa-lg")
          = check.name
        %p
          - options = check.manual? ? {} : { target: :_blank, rel: :noreferrer }
          = link_to(check.url, options) do
            visit #{check.service}
            %span.fas.fa-external-link-alt
      .card-actions
        - params = { check: { refresh: true } }
        = button_to(check_path(check, params), method: :patch) do
          = icon("fas", "sync-alt")
        = link_to(edit_check_path(check)) do
          = icon("fas", "pen")
        - confirm = "delete check? #{check.name}"
        - form_data = { data: { turbo: true, turbo_confirm: confirm } }
        = button_to(check_path(check), method: :delete, form: form_data) do
          = icon("far", "trash-alt")

app/views/checks/edit.html.haml
%h1
  Editing Check:
  %em= check.name

= form_with(model: check) do |form|
  - if check.errors.any?
    .error-explanation
      %h2 #{pluralize(check.errors.count, "error")} problems with your signup:
      %ul
        - check.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label(:name)
    = form.text_field(:name, required: true)

  = form.fields_for(:target) do |target_form|
    .field
      = target_form.label(:value, "Target")
      = target_form.number_field(:value, required: true)

    .field
      = target_form.label(:delta)
      = target_form.number_field(:delta, required: true)

    .field
      = target_form.label(:goal_value, "Goal Target")
      = target_form.number_field(:goal_value, required: true)

  .actions
    = form.submit("Update Check")

app/views/checks/index.html.haml
.header
  = link_to("+ New Check", new_check_path, class: "btn-primary new-check-btn")

- active_checks, inactive_checks = checks.partition(&:active?)

.active
  %h2 Active Checks

  - if active_checks.any?
    = render("list", checks: active_checks)
  - else
    %h3 Congrats you have no active checks!

    - if unreached_goal_targets.any?
      There are checks with unreached goals.
      = button_to("Refresh 1 Target",
        target_refreshes_path(checks: "one"),
        remote: false,
        class: "btn-primary")

      - if unreached_goal_targets.many?
        = button_to("Refresh All #{unreached_goal_targets.count} Targets",
          target_refreshes_path(checks: "all"),
          remote: false,
          class: "btn-primary")

.inactive
  %hr
  %h2 Inactive Checks

  = render("list", checks: inactive_checks)

app/views/checks/new.html.haml
.header
  %h2 Pick an integration

.card-list
  .card
    %h3
      %i.fab.fa-trello.fa-lg
      = link_to("Trello", new_trello_integration_path)
  .card
    %h3
      %i.fab.fa-github.fa-lg
      = link_to("GitHub", new_github_integration_path)
  .card
    %h3
      = link_to("manual", new_manual_integration_path)